#!/bin/bash

OWN=`ls -ld .|awk -F" " '{print $3"."$4}'`
chown -R $OWN jbxl

git pull
chown -R $OWN jbxl

# jbxl
if [ -d jbxl ]; then
    (cd jbxl; git pull)
else
    git clone https://github.com/JunkBox-Library/jbxl-php.git jbxl
    cd include
    ln -s ../jbxl/jbxl_moodle_tools.php .
    ln -s ../jbxl/jbxl_tools.php .
    ln -s ../jbxl/tools.func.php .
    cd ..
fi
chown -R $OWN jbxl

if [ -d flotsam_XmlRpcGroup ]; then
    (cd flotsam_XmlRpcGroup; git pull)
else
    git clone https://github.com/MTSGJ/flotsam_XmlRpcGroup.git
    cd helper
    ln -s ../flotsam_XmlRpcGroup/xmlrpc.php .
    ln -s ../flotsam_XmlRpcGroup/xmlrpci.php .
    ln -s ../flotsam_XmlRpcGroup/xmlgroups.php .
    ln -s ../flotsam_XmlRpcGroup/phpxmlrpclib .
    cd ../include
    ln -s ../flotsam_XmlRpcGroup/xmlgroups_config.php .
    cd ..
fi
chown -R $OWN flotsam_XmlRpcGroup

if [ -d opensim.phplib ]; then
    (cd opensim.phplib; git pull)
else
    git clone https://github.com/MTSGJ/opensim.phplib.git
    cd include
    ln -s ../opensim.helper/map_script.php .
    ln -s ../opensim.phplib/mysql.func.php .
    ln -s ../opensim.phplib/opensim.mysql.basicsearch.php .
    ln -s ../opensim.phplib/opensim.mysql.osprofile.php .
    ln -s ../opensim.phplib/opensim.mysql.ossearch.php .
    ln -s ../opensim.phplib/opensim.mysql.php .
    ln -s ../opensim.phplib/opensim.mysql.userprofile.php .
    cd ..
fi
chown -R $OWN flotsam_XmlRpcGroup

if [ -d opensim.helper ]; then
    (cd opensim.helper; git pull)
else
    git clone https://github.com/MTSGJ/opensim.helper.git
    cd helper
    ln -s ../opensim.helper/currency.php .
    ln -s ../opensim.helper/helpers.php .
    ln -s ../opensim.helper/landtool.php .
    ln -s ../opensim.helper/loginpage.php .
    ln -s ../opensim.helper/loginscreen .
    ln -s ../opensim.helper/loginscreen.php .
    ln -s ../opensim.helper/offline.php .
    ln -s ../opensim.helper/region_image.php .
    cd ../include
    ln -s ../opensim.helper/map_script.php .
    cd ..
fi
chown -R $OWN opensim.helper

if [ -d opensim.modules ]; then
    #svn update opensim.modules
    (cd opensim.modules; git pull)
else
    #svn co http://www.nsl.tuis.ac.jp/svn/opensim/opensim.modules/trunk opensim.modules
    git clone https://github.com/MTSGJ/opensim.modules.git
fi

[ -f helper/mute.php ]            || cp opensim.modules/Messaging/php/mute.php helper/mute.php
[ -f helper/profile.php ]         || cp opensim.modules/Profile/php/profile.php helper/profile.php
[ -f helper/parser.php ]          || cp opensim.modules/Search/php/parser.php helper/parser.php
[ -f helper/query.php ]           || cp opensim.modules/Search/php/query.php helper/query.php
[ -f helper/register.php ]        || cp opensim.modules/Search/php/register.php helper/register.php
[ -f helper/cron_search.php ]     || cp opensim.modules/Search/php/cron_search.php helper/cron_search.php

[ -f include/profile_config.php ] || cp opensim.modules/Profile/php/profile_config.php include/profile_config.php
[ -f include/search_config.php ]  || cp opensim.modules/Search/php/search_config.php include/search_config.php
[ -f include/message_config.php ] || cp opensim.modules/Messaging/php/message_config.php include/message_config.php

